// Generates components/scene/campusData.ts from OpenStreetMap: the LPU-Batangas campus edge and the
// houses around it (placed as Kenney City Builder buildings). Map data © OpenStreetMap contributors (ODbL).
//
//   node scripts/campus-data.mjs            # fetches from the Overpass API
//   node scripts/campus-data.mjs osm.json   # or reads a saved Overpass response
//
// Scene frame: metres from the campus pin (13.7637974 N, 121.0652952 E), +x east, +z south, rotated 10°
// so the campus buildings (bearing ≈ 10°) sit on the grid.
import fs from 'node:fs';

const LAT0 = 13.7637974;
const LON0 = 121.0652952;
const PHI = (10 * Math.PI) / 180;
const MLAT = 111320;
const MLON = 111320 * Math.cos((LAT0 * Math.PI) / 180);
const QUERY = `[out:json][timeout:60];(way(around:350,${LAT0},${LON0})["building"];way(91386590););out geom tags;`;

const src = process.argv[2]
  ? JSON.parse(fs.readFileSync(process.argv[2], 'utf8'))
  : await (await fetch('https://overpass-api.de/api/interpreter', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'parada-landing campus-data script' },
      body: 'data=' + encodeURIComponent(QUERY),
    })).json();

const toScene = ({ lat, lon }) => {
  const x = (lon - LON0) * MLON;
  const z = -(lat - LAT0) * MLAT;
  return [x * Math.cos(PHI) + z * Math.sin(PHI), -x * Math.sin(PHI) + z * Math.cos(PHI)];
};
const r1 = (v) => Math.round(v * 10) / 10;

const campus = src.elements.find((e) => e.id === 91386590);
const edge = campus.geometry.map(toScene);
const inside = ([x, z]) => {
  let hit = false;
  for (let i = 0, j = edge.length - 1; i < edge.length; j = i++) {
    const [xi, zi] = edge[i];
    const [xj, zj] = edge[j];
    if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) hit = !hit;
  }
  return hit;
};

// Street corridors kept clear (scene frame, see layout.ts): west road x≈-88, north road z≈-76, east road x≈+84.
const onStreet = ([x, z]) => Math.abs(x + 88) < 9 || (Math.abs(z + 76) < 9 && x > -96 && x < 92) || (Math.abs(x - 84) < 9 && z > -84);

const houses = [];
for (const e of src.elements) {
  if (!e.tags?.building || e.id === 91386590 || !e.geometry) continue;
  const pts = e.geometry.map(toScene);
  const c = pts.reduce((a, p) => [a[0] + p[0] / pts.length, a[1] + p[1] / pts.length], [0, 0]);
  if (Math.abs(c[0]) > 150 || c[1] < -125 || c[1] > 180 || inside(c) || onStreet(c)) continue;
  // footprint axes from the longest edge
  let best = 0;
  let ang = 0;
  for (let i = 1; i < pts.length; i++) {
    const L = Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]);
    if (L > best) [best, ang] = [L, Math.atan2(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1])];
  }
  const ux = [Math.sin(ang), Math.cos(ang)];
  const proj = (u) => pts.map((p) => (p[0] - c[0]) * u[0] + (p[1] - c[1]) * u[1]);
  const a = proj(ux);
  const b = proj([ux[1], -ux[0]]);
  const w = Math.max(...a) - Math.min(...a);
  const d = Math.max(...b) - Math.min(...b);
  if (w * d < 25) continue;
  houses.push([r1(c[0]), r1(c[1]), r1(w), r1(d), Math.round(((ang % (Math.PI / 2)) + Math.PI / 2) % (Math.PI / 2) * 100) / 100, Number(e.tags['building:levels']) || 0]);
}
houses.sort((p, q) => Math.hypot(p[0], p[1] - 40) - Math.hypot(q[0], q[1] - 40));

const out = `// Generated by scripts/campus-data.mjs from OpenStreetMap. Map data © OpenStreetMap contributors (ODbL).
// Do not edit by hand. Scene frame: metres, +x east, +z south, rotated 10° (see layout.ts).

/** Campus boundary (OSM way 91386590). */
export const CAMPUS_EDGE: [number, number][] = ${JSON.stringify(edge.map(([x, z]) => [r1(x), r1(z)]))};

/** Buildings around the campus, nearest first: [x, z, width, depth, yaw (0..π/2), levels or 0]. */
export const HOUSES: [number, number, number, number, number, number][] = ${JSON.stringify(houses)};
`;
fs.writeFileSync(new URL('../components/scene/campusData.ts', import.meta.url), out);
console.log(`campus edge ${edge.length} pts, ${houses.length} buildings`);
